CREATE DATABASE EscolaTeste;
USE EscolaTeste;

CREATE TABLE TBL_NOMEALUNO( 
	COD_ALUNO SMALLINT IDENTITY NOT NULL,
	NOME_ALUNO VARCHAR(30) NOT NULL, 
	NOTA1 TINYINT NOT NULL,
	NOTA2 TINYINT NOT NULL, 
	NOTA3 TINYINT NOT NULL,
	NOTA4 TINYINT NOT NULL,
	CONSTRAINT PK_COD_ALUNO PRIMARY KEY (COD_ALUNO)
);


INSERT INTO TBL_NOMEALUNO (NOME_ALUNO, NOTA1, NOTA2, NOTA3, NOTA4)
VALUES 
('JOÃO', 5.6, 7.4, 5.3, 4.9),
('PAULO',5.3, 8.4, 3.3, 5.9),
('MARIA',9.3, 6.4, 3.1, 5.7),
('MARTA',8.3, 4.4, 7.3, 6.9);

SELECT * FROM TBL_NOMEALUNO WHERE NOME_ALUNO = ('JOÃO')


--Funções escalares

GO
CREATE FUNCTION nota_media(@nome VARCHAR(30))
RETURNS REAL
AS 
BEGIN
	DECLARE @media REAL
	SELECT @media = (nota1 + nota2 + nota3 + nota4 * 2) / 5 FROM TBL_NOMEALUNO
	WHERE NOME_ALUNO = @nome
	RETURN @media
END

GO
SELECT dbo.nota_media ('Maria')

